include:
  - component: $CI_SERVER_FQDN/base-ci-components/base/gitlab-ci-base@main
  - .gitlab/ci/node.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROD_REF: /^(release)/
  INTEG_REF: /^(main|development)$/

stages:
- build
- test
- package-build
- package-test
- infra
- deploy
- acceptance
- publish
- infra-prod
- production
