include:
  - component: $CI_SERVER_FQDN/base-ci-components/base/gitlab-ci-base@main

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROD_REF: /^(release)/
  INTEG_REF: /^(main|development)$/

citrineos-core:
  needs: []
  stage: base
  trigger:
    include: .gitlab/ci/citrine-*.gitlab-ci.yml
  rules:
    - changes:
      - citrineos-core/**/*

stages:
- base # just for monorepo aproach
- build
- test
- package-build
- package-test
- infra
- deploy
- acceptance
- publish
- infra-prod
- production
