include:
  # - component: $CI_SERVER_FQDN/base-ci-components/base/gitlab-ci-base@main
  - local: .gitlab/ci/node.gitlab-ci.yml
    rules:
      - changes:
        - citrineos-core/**/*

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROD_REF: /^(release)/
  INTEG_REF: /^(main|development)$/

stages:
- build
- test
- package-build
- package-test
- infra
- deploy
- acceptance
- publish
- infra-prod
- production

vars:
  stage: build
  script: env | sort
