[secrets]
  [[secrets.ruleset]]
    disable = true
    [secrets.ruleset.identifier]
      type  = "gitleaks_rule_id"
      value = "RSA private key"
    [secrets.ruleset.identifier]
      type  = "gitleaks_rule_id"
      value = "PKCS8 private key"