# secret-detection-ruleset.toml

# General configuration
[config]
enabled = true

# Ignoring specific files that contain known secrets (as needed for testing or other purposes)
[[whitelist]]
files = [
    "citrineos-core/02_Util/test/resources/LeafKeySample.pem",
    "citrineos-core/02_Util/test/resources/RootKeySample.pem",
    "citrineos-core/02_Util/test/resources/SubCAKeySample.pem",
    "citrineos-core/Server/src/assets/certificates/acme_account_key.pem",
    "citrineos-core/Server/src/assets/certificates/leafKey.pem",
    "citrineos-core/Server/src/assets/certificates/subCAKey.pem",
    "citrineos-core/Swarm/src/assets/certificates/acme_account_key.pem",
    "citrineos-core/Server/src/config/envs/docker.ts",
    "citrineos-core/Server/src/config/envs/local.ts",
    "citrineos-core/Server/src/config/envs/swarm.docker.ts",
    "citrineos-core/Swarm/src/config/envs/docker.ts",
    "citrineos-core/Swarm/src/config/envs/local.ts"
]

# Additional pattern-based whitelisting (if exact files cannot be used)
patterns = [
    "-----BEGIN PRIVATE KEY-----",  # Generic pattern for private keys
    "amqp://guest:guest@",          # AMQP URL with guest credentials
    "-----BEGIN RSA PRIVATE KEY-----" # Pattern for RSA private keys
]
