name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_PROJECT_DIR: citrineos-core
  NODE_VERSION: 18

jobs:
  changes-citrineos:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect-changes-citrineos.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Detect change in CitrineOS dir
        id: detect-changes-citrineos
        uses: tj-actions/changed-files@v42
        with:
          files: ${{ env.NODE_PROJECT_DIR }}/**

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Build
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run build

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-build-artifacts
          path: ${{ env.NODE_PROJECT_DIR }}/dist

  unit-test:
    needs: [ changes-citrineos ]
    if: needs.changes-citrineos.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Run Unit Tests
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run test
        continue-on-error: true

  lint:
    needs: [ changes-citrineos ]
    if: needs.changes-citrineos.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all
        
      - name: Lint Code
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run lint

  npm-audit:
    needs: [build, unit-test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Audit Packages
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm audit --audit-level=low
        continue-on-error: true

  npm-outdated:
    needs: [build, unit-test, lint]
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/release')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

  njsscan:
    needs: [build, unit-test, lint]
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Install njsscan
        run: pip3 install --upgrade njsscan

      - name: Run njsscan
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: njsscan .
