name: Node.js CI/CD Pipeline

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_PROJECT_DIR: citrineos-core
  NODE_VERSION: '18'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Build
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run build

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-build-artifacts
          path: ${{ env.NODE_PROJECT_DIR }}/dist

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Run Unit Tests
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        continue-on-error: true
        run: npm run test

  lint:
    needs: build
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Lint
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        continue-on-error: true
        run: npm run lint

  npm-audit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Audit Packages
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        continue-on-error: true
        run: npm audit --audit-level=low

  npm-outdated:
    needs: build
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/release')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Check outdated packages
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        continue-on-error: true
        run: npm outdated --omit=dev

  njsscan:
    needs: build
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.NODE_PROJECT_DIR }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install njsscan
        run: pip3 install --upgrade njsscan

      - name: Install dependencies
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: npm run install-all

      - name: Run njsscan
        working-directory: ${{ env.NODE_PROJECT_DIR }}
        run: njsscan .
